:PROPERTIES:
:ID:       dfe9b15b-1eb7-4068-9d1d-9ac0ae4682e5
:END:
#+title: Good Retro Gaming YouTubers
#+filetags: :Gaming:
#+date: <2022-02-14 Mon 08:52>

These are content creators who do excellent in depth videos on retro games. Rather then be angry ranters or do a lot silly skits [fn:2]. These are extremly educational and teach a lot about the contraints involved and the design of retro games.

I will group them into various categories for convience, but some of them do occasional videos on other aspects. I will also add inactive ones since this content is basically timeless. 

This is a evolving document, its basically my written out Youtube subscriptions but with more detail. This only includes the ones I have actually watched.

# might include channel links sorted by most popular https://www.youtube.com/c/OddTinkering/videos?view=0&sort=p&flow=grid

* The exploiters

These focus on exploring the game logic and breaking and glitching it to do awesome things. Weather that be to be stuck in a level for 478 years, giving Mario a laser sword or creating a dissembler in Super Mario World.

Most of these people who focus on one game or series.

** UncommentatedPannen / PannenKoek (Mario 64)

There mainly famous as being [[https://knowyourmeme.com/memes/people/pannenkoek2012][the subject of numerous memes]]. Their videos are extremly in depth analysis of Mario 64's mechanics (spoiler: its a amazing world).

Their main goal is to beat Mario 64 without ever jumping (no A presses). They have made tremendous progress over the years and their down to ~30 press for 100% completion.

I recommend you watch their older other channel that has commentary. It is highly entertaining.

I love Mario 64 so much more after seeing their videos.

** Stryder7x (Paper Mario)

All their videos have commentary and their videos are very well produced. I personally enjoyed their "X Crashes Paper Mario" Series.

** Pokemon

I personally don't watch many of them so I have fewer words to say.

From what I understand most of them are affliated with [[https://archives.glitchcity.info/][Glitch City Laboratories]], which was a website (now a Discord) focused on hacking old Pokemon games. Some Youtubers include ChickasaurusGL and TheZZAZZGlitch. I don't know of any of them who have commentary.

The one that I mostly watch is Pikasprey Yellow (its commented) who mainly focuses on elaborate softlocks, situations where its impossible to escape without wiping out your whole game.

** Redfuzzydice (Mario Sunshine)

I am a bit wary of inclusion as [[https://www.youtube.com/watch?v=puNJumkuIUw][the creator apparently has a history of lying and plagiarism]] particulary among the Super Smash Brothers Melee community, So I am not including their more popular melee channel [fn:1].

I doubt most of the information is inaccurate in their videos. So I still recommend. Its commented and very watchable.

* The speedrunners

Like exploiters they focus on breaking the game but for one specific aim. To get the *fastest time humanely possible*.

I am excluding the player-centric and news channel since that is not as timeless but those YouTubers are good and worth checking as well.

** Omnigamer

Their computer engineer by trade and are highly knoweleadge about how to exploit video games ([[https://www.fangamer.com/products/speedrun-book][You should probably buy their book about this]])

Their their for being the exposing speed run frauds like Atari Dragster. They have many videos on this.

** The Frame Savers

Inactive podcast on speed running. The focus on channel was about speedrunning techniques for certain games (usually niche ones their interested ones). They almost never talked about the players or the history of world record.

** Summoning Salt

It is very player-centric but it does go into a lot of technical detail for the various games. I personally like the Mario Kart videos.

** Speedlore

In depth analysis of goldenEye and perfect Dark speedruns and strategies. I am excluding their main channel as it focuses too much on the human interest aspect and news too much.

Note these are live streams and are quite long.

* The ROM hackers

These people focus on using retro games as a platform to build their own games on to.

** Kaze Emanuar (Mario 64)

Their YouTube is mainly showcasing their various projects but Twitch streams show them developing the games. 

* Hardware hackers
** Rainbow Repair

They fix and enhance Gameboys. I find it interesting how much people have enhanced their gameboys (adding backlit displays, batteries).

** Odd Tinkering

#+begin_quote
No annoying music, no talking, plenty of info, beautiful shots, masterful work. - youTube comment
#+end_quote

Very popular channel focused on restoration. It is uncommented and ASMR focused (which I am not the biggest fan of). Their descriptions are very useful and explains what they do so be sure to read them.

It has paid promotions but thankfully those aren't commented which is extremly refreshing.

See also their second channel [[https://www.youtube.com/channel/UCL5OpT5ewaPBpfroIJ4HbFw/videos][Odd Experiments]].

* Emulation

/Disclaimer: I personally dont watch any content on Emulation/

** Modern Vintage Gamer

They focus on emulation developments and progress (and some videos on console hacking). Their videos are very well done.

* Programmers
** Gamehut

They were one of the main developers of Sonic R and their still active in the demoscene community.

** Retro Game Mechanics Explained
** Bisqwit

They do Video Game Videos anymore.

** Displaced Gamers
* Musicians

This is what I currently mainly watch.

** GST
** 8 Bit Music Theory

This focus on the compostional aspect. My favorite video of theirs is the video on Chrono Trigger.

** Sound Sack
** Yuzo Koshiro

Yes Yuzo Koshiro has a YouTube. Hes is probably the biggest VGM artist of his time.

** Malcom Robinson Music
* Historians
** strafefox
** Gaming Historian
* Wizards

"WTF how is that possible"

** Suckerpinch
* Footnotes

[fn:2] My biggest problem with these types of YouTubers is (1) if their videos aren't funny its extremly painful to watch and (2) so many of them are extremely uninformed about their given topic that its super annoying to watch. Finding YouTubers in categories listed here is always a joy.

[fn:1] Though by all means watch what you want, just be wary of accepting their personal claims.
